CREATE TABLE EMPLOYEE(SSN VARCHAR(8),
Name VARCHAR(10),
Address VARCHAR(30),
Sex CHAR(2),
Salary NUMBER(10),SuperSSN VARCHAR(8),DNo VARCHAR(6),
CONSTRAINT PK_SSN PRIMARY KEY(SSN));

CREATE TABLE DEPARTMENT(DNo VARCHAR(6),
DName VARCHAR(10),
MgrSSN VARCHAR(8),
MgrStartDate DATE,
CONSTRAINT PK_DNo PRIMARY KEY(DNo),
CONSTRAINT FK_MgrSSN FOREIGN KEY(MgrSSN) REFERENCES EMPLOYEE(SSN));

CREATE TABLE DLOCATION(DNo VARCHAR(6),
DLoc VARCHAR(15),
CONSTRAINT PK_DNo_DLoc PRIMARY KEY(DNo,DLoc),
CONSTRAINT FK_DNo FOREIGN KEY(DNo) REFERENCES DEPARTMENT(DNo));

CREATE TABLE PROJECT(PNo VARCHAR(5),
PName VARCHAR(10),
PLocation VARCHAR(14),
DNo VARCHAr(6),
CONSTRAINT PK_PNo PRIMARY KEY(PNo),
CONSTRAINT FK_PDNo FOREIGN KEY(DNo) REFERENCES DEPARTMENT(DNo));

CREATE TABLE WORKS_ON(SSN VARCHAR(8),
PNo VARCHAR(5),
Hours NUMBER(5),
CONSTRAINT PK_PNo_SSN PRIMARY KEY(PNo,SSN),
CONSTRAINT FK_WSSN FOREIGN KEY(SSN) REFERENCES EMPLOYEE(SSN),
CONSTRAINT FK_PNo FOREIGN KEY(PNo) REFERENCES PROJECT(PNo));

ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_SSN FOREIGN KEY(SuperSSN) REFERENCES EMPLOYEE(SSN);
ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EDNo FOREIGN KEY(DNo) REFERENCES DEPARTMENT(DNo);