CREATE TABLE STUDENT (USN VARCHAR (10),
SNAME VARCHAR (20),
ADDRESS VARCHAR (20),
PHONE NUMBER (10),
GENDER CHAR (1),
CONSTRAINT PKST PRIMARY KEY(USN));

CREATE TABLE SEMSEC (SSID VARCHAR (5),
SEM NUMBER (2),
SEC CHAR (1),
CONSTRAINT PKSEM PRIMARY KEY(SSID));
CREATE TABLE CLASS (USN VARCHAR (10),
SSID VARCHAR (5),
CONSTRAINT PKCL PRIMARY KEY (USN, SSID),
CONSTRAINT FKUSN FOREIGN KEY (USN) REFERENCES STUDENT (USN),
CONSTRAINT FKSSID FOREIGN KEY (SSID) REFERENCES SEMSEC (SSID));

CREATE TABLE SUBJECT (SUBCODE VARCHAR (8),
TITLE VARCHAR (20),
SEM NUMBER (2),
CREDITS NUMBER (5),
CONSTRAINT PKSUB PRIMARY KEY (SUBCODE));

CREATE TABLE IAMARKS (USN VARCHAR (10),
SUBCODE VARCHAR (8),
SSID VARCHAR (5),
TEST1 NUMBER,
TEST2 NUMBER,
TEST3 NUMBER,
FINALIA NUMBER,
CONSTRAINT PKIA PRIMARY KEY (USN, SUBCODE, SSID),
CONSTRAINT FKUS FOREIGN KEY (USN) REFERENCES STUDENT (USN),
CONSTRAINT FKSU FOREIGN KEY (SUBCODE) REFERENCES SUBJECT (SUBCODE),
CONSTRAINT FKSSI FOREIGN KEY (SSID) REFERENCES SEMSEC (SSID));
